### ISSUE TITLE
Invalid memory address or nil pointer dereference when configuring Grafana

### ISSUE THREAD

**Issue by smileisak** [k8spin/loki-multi-tenant-proxy#1]
First Issue ! Yes i'm trying this `loki-multi-tenant-proxy`. I've built and deployed it in a GKE cluster with the logging operator installed.

The issue is related to relation between Grafana and `loki-multi-tenant-proxy`. When adding a datasource from Grafana interface to point to `loki-multi-tenant-proxy` internal service it crashed the `loki-multi-tenant-proxy` pod. Here is some details about the error:

```bash
2020/02/07 14:04:39 172.20.128.143:43402 GET /api/prom/label?
2020/02/07 14:04:39 http: panic serving 172.20.128.143:43402: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc00014c0a0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x7b8160, 0xb37b20)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/angelbarrera92/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy.isAuthorized(0xc00001a500, 0x4, 0xc00001a505, 0x13, 0x0, 0xc000144e01, 0xc0000ae080, 0xb44b20)
	/go/src/github.com/k8spin/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy/auth.go:34 +0x3a
github.com/angelbarrera92/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy.BasicAuth.func1(0x8a89e0, 0xc00016c1c0, 0xc000150100)
	/go/src/github.com/k8spin/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy/auth.go:23 +0x9c
github.com/angelbarrera92/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy.LogRequest.func1(0x8a89e0, 0xc00016c1c0, 0xc000150100)
	/go/src/github.com/k8spin/loki-multi-tenant-proxy/internal/app/loki-multi-tenant-proxy/logging.go:12 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc000082ed0, 0x8a89e0, 0xc00016c1c0, 0xc000150100)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xb44a40, 0x8a89e0, 0xc00016c1c0, 0xc000150100)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000088ea0, 0x8a89e0, 0xc00016c1c0, 0xc000150100)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00014c0a0, 0x8a9620, 0xc00001e340)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

This is manifests used to install the `loki-multi-tenant-proxy`.

__Deployment__:

```yaml
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: loki-multi-tenant-proxy
  namespace: logging
spec:
  selector:
    matchLabels:
      app: loki-multi-tenant-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: loki-multi-tenant-proxy
    spec:
      containers:
      - name: loki-multi-tenant-proxy
        image: dtr-dev.dt.renault.com/j2c/loki-multi-tenant-proxy:1.0
        command: ["./loki-multi-tenant-proxy"]
        args: 
          - "run"
          - "--loki-server" 
          - "http://loki.logging.svc.cluster.local:3100"
          - "--port" 
          - "3501" 
          - "--auth-config"
          - "/loki-multi-tenant-proxy/config/multi-tenant.yaml"
        volumeMounts:
        - name: loki-multi-tenant-proxy-config
          mountPath: /etc/config
        resources:
          limits:
            cpu: "20m"
            memory: 100Mi
          requests:
            cpu: "20m"
            memory: 100Mi
      volumes:
      - name: loki-multi-tenant-proxy-config
        configMap:
          name: loki-multi-tenant-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki-multi-tenant-proxy
  name: loki-multi-tenant-proxy
  namespace: logging
spec:
  ports:
  - name: http
    port: 3501
    protocol: TCP
    targetPort: 3501
  selector:
    app: loki-multi-tenant-proxy
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: loki-multi-tenant-proxy
  name: loki-multi-tenant-proxy-config
  namespace: logging
data:
  multi-tenant.yaml: |
    users:
    - username: loki1
      password: strongpassword
      orgid: logging
```

And finally, the grafana configuration:

![Screenshot 2020-02-07 at 15 10 49](https://user-images.githubusercontent.com/3457118/74036197-13051180-49bc-11ea-8106-8f9612de6953.png)

**Comment by angelbarrera92** [comment]
Hi @smileisak, seems like you are not using your configuration file. (Yes, the error handling could be better)

Change:
from:
```
        args: 
          - "run"
          - "--loki-server" 
          - "http://loki.logging.svc.cluster.local:3100"
          - "--port" 
          - "3501" 
          - "--auth-config"
          - "/loki-multi-tenant-proxy/config/multi-tenant.yaml"
        volumeMounts:
        - name: loki-multi-tenant-proxy-config
          mountPath: /etc/config
```
to
```
        args: 
          - "run"
          - "--loki-server" 
          - "http://loki.logging.svc.cluster.local:3100"
          - "--port" 
          - "3501" 
          - "--auth-config"
          - "/etc/config/multi-tenant.yaml"
        volumeMounts:
        - name: loki-multi-tenant-proxy-config
          mountPath: /etc/config
```

Thanks!

**Comment by smileisak** [comment]
@angelbarrera92 You are right ! i've changed the config but i get an orror in grafana, `Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.`

It looks like the proxy does not send the request with the `org-id` header.

Here is the configuration of loki:

```yaml
  auth_enabled: true  
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1

      ## Different ring configs can be used. E.g. Consul
      # ring:
      #   store: consul
      #   replication_factor: 1
      #   consul:
      #     host: "consul:8500"
      #     prefix: ""
      #     httpclienttimeout: "20s"
      #     consistentreads: true
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v9
      index:
        prefix: index_
        period: 168h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb:
      directory: /data/loki/index
    filesystem:
      directory: /data/loki/chunks
  chunk_store_config:
    max_look_back_period: 0
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0
```

<img width="1025" alt="Screenshot 2020-02-07 at 16 51 10" src="https://user-images.githubusercontent.com/3457118/74043803-56ff1300-49ca-11ea-99ef-b1d1a1fa35bb.png">
Nothing in the proxy logs:

```bash

 k logs -f -n logging loki-multi-tenant-proxy-749dffb576-qrdsq
2020/02/07 15:48:31 172.20.132.223:48660 POST /loki/api/v1/push
2020/02/07 15:48:33 172.20.128.143:54756 GET /api/prom/label?
2020/02/07 15:49:02 172.20.128.143:54934 GET /api/prom/label?
2020/02/07 15:49:03 172.20.128.143:54942 GET /api/prom/label?
2020/02/07 15:49:13 172.20.128.143:54942 GET /api/prom/label?start=1581068953242000000&end=1581090553242000000
2020/02/07 15:49:14 172.20.128.143:55012 GET /api/prom/label?
2020/02/07 15:49:14 172.20.128.143:55012 GET /api/prom/label/namespace/values?start=1581068953242000000&end=1581090553242000000
2020/02/07 15:49:31 172.20.132.223:48868 POST /loki/api/v1/push
2020/02/07 15:50:31 172.20.132.223:49074 POST /loki/api/v1/push
2020/02/07 15:50:47 172.20.128.143:55702 GET /api/prom/label?
2020/02/07 15:51:32 172.20.132.223:49318 POST /loki/api/v1/push
2020/02/07 15:52:32 172.20.132.223:49532 POST /loki/api/v1/push
2020/02/07 15:53:32 172.20.132.223:49736 POST /loki/api/v1/push
```

neither in grafana logs.
